import csv
import io
from datetime import datetime
from fastapi import APIRouter, Depends, HTTPException, Query, Response
from sqlalchemy.orm import Session
from typing import Optional, List, Dict, Any

from ..database import get_db
from ..models import ScreeningCase, User
from ..schemas import ScreeningCaseOut
from ..services.audit_service import log_audit_event
from .auth import get_current_user
from .screenings import _format_case_out

router = APIRouter(prefix="/reports", tags=["Reports"])

@router.get("")
def list_reports(
    status: Optional[str] = Query(None),
    risk_level: Optional[str] = Query(None),
    doc_type: Optional[str] = Query(None),
    search: Optional[str] = Query(None),
    db: Session = Depends(get_db)
):
    query = db.query(ScreeningCase)
    if status and status != "ALL":
        query = query.filter(ScreeningCase.status == status)
    if risk_level and risk_level != "ALL":
        query = query.filter(ScreeningCase.overall_risk_level == risk_level)
    if doc_type and doc_type != "ALL":
        query = query.filter(ScreeningCase.document_type == doc_type)
    if search:
        query = query.filter(
            (ScreeningCase.id.ilike(f"%{search}%")) |
            (ScreeningCase.extracted_data_json.ilike(f"%{search}%"))
        )

    cases = query.order_by(ScreeningCase.created_at.desc()).all()
    formatted = [_format_case_out(c) for c in cases]

    # Calculate summary metrics for reports
    total = len(cases)
    verified = sum(1 for c in cases if c.status == "VERIFIED")
    flagged = sum(1 for c in cases if c.status == "FLAGGED")
    in_review = sum(1 for c in cases if c.status == "IN_REVIEW")
    high_risk = sum(1 for c in cases if c.overall_risk_level == "HIGH")

    return {
        "summary": {
            "total_reports": total,
            "verified_count": verified,
            "flagged_count": flagged,
            "in_review_count": in_review,
            "high_risk_count": high_risk
        },
        "reports": formatted
    }

@router.get("/{case_id}")
def get_report_detail(case_id: str, db: Session = Depends(get_db)):
    case = db.query(ScreeningCase).filter(ScreeningCase.id == case_id).first()
    if not case:
        raise HTTPException(status_code=404, detail=f"Report for case {case_id} not found")
    
    formatted = _format_case_out(case)
    return {
        "report_id": f"REP-{case.id}",
        "generated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "compliance_disclaimer": "AI-Assisted Assessment Notice: This screening report is generated by VERINEX strictly for defensive identity verification and risk assessment decision support. Results do not constitute absolute legal certainty.",
        "case_data": formatted
    }

@router.get("/{case_id}/export")
def export_report(
    case_id: str,
    format: str = Query("json", pattern="^(json|csv)$"),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    case = db.query(ScreeningCase).filter(ScreeningCase.id == case_id).first()
    if not case:
        raise HTTPException(status_code=404, detail=f"Case {case_id} not found")

    log_audit_event(
        db=db,
        username=current_user.full_name,
        action="EXPORT_REPORT",
        case_id=case.id,
        details=f"Exported screening report in {format.upper()} format.",
        severity="INFO"
    )

    data = _format_case_out(case)

    if format == "csv":
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(["Field", "Value"])
        writer.writerow(["Report ID", f"REP-{case.id}"])
        writer.writerow(["Case ID", case.id])
        writer.writerow(["Document Type", case.document_type])
        writer.writerow(["Status", case.status])
        writer.writerow(["Risk Level", case.overall_risk_level])
        writer.writerow(["Risk Score", case.risk_score])
        writer.writerow(["AI Confidence", f"{case.ai_confidence}%"])
        writer.writerow(["Quality Score", f"{case.document_quality_score}%"])
        writer.writerow(["OCR Confidence", f"{case.ocr_confidence}%"])
        writer.writerow(["Holder Name", data["extracted_data"].get("full_name", "")])
        writer.writerow(["Document Number", data["extracted_data"].get("document_number", "")])
        writer.writerow(["DOB", data["extracted_data"].get("date_of_birth", "")])
        writer.writerow(["Expiry Date", data["extracted_data"].get("expiry_date", "")])
        writer.writerow(["Reviewer", case.reviewer_name or "Unassigned"])
        writer.writerow(["Created At", case.created_at.strftime("%Y-%m-%d %H:%M:%S")])

        return Response(
            content=output.getvalue(),
            media_type="text/csv",
            headers={"Content-Disposition": f"attachment; filename=VERINEX_Report_{case.id}.csv"}
        )

    # JSON export
    return {
        "report_metadata": {
            "system": "VERINEX AI-Based Identity & Document Screening System",
            "version": "1.0.0",
            "generated_by": current_user.full_name,
            "export_timestamp": datetime.utcnow().isoformat()
        },
        "case_report": data
    }
